AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Ingest Framework repository
Parameters:
  StackVersion:
    Type: String
    Description: The version of the stack.
  RepositoryName:
    Type: String
    Default: ingest-framework-repository
Resources:

######
# ECR
######
  IngestFrameworkRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      Tags:
        - Key: Environment
          Value: production
        - Key: Version
          Value: !Ref StackVersion
